### ISSUE TITLE
No Resource Pack Found ? 

### ISSUE THREAD

**Issue by CarlucciMods** [Coliwogg/Gems-And-Crystals#2] opened 2019-12-15 02:40 UTC
![7777](https://user-images.githubusercontent.com/31194015/70857328-421a6d80-1eba-11ea-91d2-4ed1bf03e092.PNG)

**Comment by Greg-21** [comment] 2020-05-04 10:05
Duplicate of: #5

**Comment by Greg-21** [comment] 2020-06-20 13:38
Fixed with version 1.2.7 for Minecraft 1.14.4.

**Closed as completed** 2020-06-20 13:50 UTC
